package com.originspecs.specextractor.config;

import com.originspecs.specextractor.model.SourceArtifactId;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class DataPrepLineageResolverTest {

    private static final UUID SAMPLE = UUID.fromString("550e8400-e29b-41d4-a716-446655440000");
    private static final UUID OTHER = UUID.fromString("6ba7b810-9dad-11d1-80b4-00c04fd430c8");

    @Test
    void shouldLeaveConfigUnchanged_whenNoSidecarExists(@TempDir Path temp) throws Exception {
        Path input = temp.resolve("book.xls");
        Files.createFile(input);
        Config base = new Config(input, Path.of("out.json"), "key", null);

        Config result = DataPrepLineageResolver.applySidecarLineage(base);

        assertThat(result).isSameAs(base);
        assertThat(result.sourceArtifactLineage()).isEmpty();
    }

    @Test
    void shouldLoadLineageFromSidecar_whenCliDidNotPassId(@TempDir Path temp) throws Exception {
        Path input = temp.resolve("book.xls");
        Files.createFile(input);
        Files.writeString(input.resolveSibling("book.xls.source-artifact-id"), SAMPLE + "\n");
        Config base = new Config(input, Path.of("out.json"), "key", null);

        Config result = DataPrepLineageResolver.applySidecarLineage(base);

        assertThat(result.sourceArtifactLineage()).contains(SourceArtifactId.parse(SAMPLE.toString()));
    }

    @Test
    void shouldUseFirstUuidLine_whenLeadingBlankLines(@TempDir Path temp) throws Exception {
        Path input = temp.resolve("book.xls");
        Files.createFile(input);
        Files.writeString(
                input.resolveSibling("book.xls.source-artifact-id"),
                "\n  \n" + SAMPLE + "\n");
        Config base = new Config(input, Path.of("out.json"), "key", null);

        Config result = DataPrepLineageResolver.applySidecarLineage(base);

        assertThat(result.sourceArtifactLineage()).contains(SourceArtifactId.parse(SAMPLE.toString()));
    }

    @Test
    void shouldSkipCommentLinesBeforeUuid(@TempDir Path temp) throws Exception {
        Path input = temp.resolve("book.xls");
        Files.createFile(input);
        Files.writeString(
                input.resolveSibling("book.xls.source-artifact-id"),
                "# generated by DataPrep\n" + SAMPLE + "\n");
        Config base = new Config(input, Path.of("out.json"), "key", null);

        Config result = DataPrepLineageResolver.applySidecarLineage(base);

        assertThat(result.sourceArtifactLineage()).contains(SourceArtifactId.parse(SAMPLE.toString()));
    }

    @Test
    void shouldIgnoreSidecar_whenNoLineParsesAsUuid(@TempDir Path temp) throws Exception {
        Path input = temp.resolve("book.xls");
        Files.createFile(input);
        Files.writeString(input.resolveSibling("book.xls.source-artifact-id"), "# no uuid on this file\n");
        Config base = new Config(input, Path.of("out.json"), "key", null);

        Config result = DataPrepLineageResolver.applySidecarLineage(base);

        assertThat(result).isSameAs(base);
        assertThat(result.sourceArtifactLineage()).isEmpty();
    }

    @Test
    void shouldReturnSameConfig_whenCliMatchesSidecar(@TempDir Path temp) throws Exception {
        Path input = temp.resolve("book.xls");
        Files.createFile(input);
        Files.writeString(input.resolveSibling("book.xls.source-artifact-id"), SAMPLE + "\n");
        SourceArtifactId cliId = SourceArtifactId.parse(SAMPLE.toString());
        Config base = new Config(input, Path.of("out.json"), "key", cliId);

        Config result = DataPrepLineageResolver.applySidecarLineage(base);

        assertThat(result).isSameAs(base);
    }

    @Test
    void shouldThrow_whenCliIdDoesNotMatchSidecar(@TempDir Path temp) throws Exception {
        Path input = temp.resolve("book.xls");
        Files.createFile(input);
        Files.writeString(input.resolveSibling("book.xls.source-artifact-id"), SAMPLE + "\n");
        SourceArtifactId cliId = SourceArtifactId.parse(OTHER.toString());
        Config base = new Config(input, Path.of("out.json"), "key", cliId);

        assertThatThrownBy(() -> DataPrepLineageResolver.applySidecarLineage(base))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("does not match")
                .hasMessageContaining(SAMPLE.toString())
                .hasMessageContaining(OTHER.toString());
    }

    @Test
    void shouldResolveSidecarPath_nextToInput() {
        Path input = Path.of("/data/out/cleaned.xls");
        Path sidecar = DataPrepLineageSidecar.pathForInputWorkbook(input);

        assertThat(sidecar.toString()).endsWith("cleaned.xls" + Constants.DATAPREP_LINEAGE_SIDECAR_SUFFIX);
    }
}
